### ISSUE TITLE
Not working with transparency background

### ISSUE THREAD

**Issue by gamoutatsumi** [Shougo/cmdline.vim#4]
## repro vimrc
```vim
set rtp+=/path/to/Shougo/cmdline.vim

highlight Normal guibg=NONE ctermbg=NONE
```

## environment

OS: macOS Sonoma 14.4.1
Vim: not repro
Neovim: master HEAD (7aa5637)

## screenshot

![image](https://github.com/Shougo/cmdline.vim/assets/47162587/73e07fe9-5158-47b2-8c59-9e84d3d1d8d5)

**Comment by Shougo** [comment]
Fixed.
