### ISSUE TITLE
When a Nerdfont character is passed as the first argument (prompt) of cmdline#input, the prompt is displayed even in the original command line that is not a window created by cmdline.vim.

### ISSUE THREAD

**Issue by kurokoji** [Shougo/cmdline.vim#5]
# Description
When a Nerdfont character is passed as the first argument (prompt) of cmdline#input, the prompt is displayed even in the original command line that is not a Window created by cmdline.vim.

# Expected behavior
- That character should not be visible.
- The expected behavior is for the cursor to appear on the command line created by cmdline.vim instead of on the original command line.

# Screenshot
![Animation](https://github.com/user-attachments/assets/5762bf00-60de-4e00-86d1-8af2be9f868c)

# Desktop

- OS: Ubuntu 22.04 LTS(WSL2)
- Vim or Neovim: Neovim v0.11.0-dev-401+gbcb17689d
- Commit: [6eefa5580a4e01b7bdd471e9080edfdcecd9fab8](https://github.com/Shougo/cmdline.vim/commit/6eefa5580a4e01b7bdd471e9080edfdcecd9fab8)
- Terminal: WezTerm(20240609-095134-f5e496eb)

## Minimal Config

- `init.vim`

``` vim
" dein {{{
let $BASE_DIR = fnamemodify(expand('<sfile>'), ':h')
let $CACHE = expand('$BASE_DIR/cache')
if !isdirectory($CACHE)
  call mkdir($CACHE, 'p')
endif

let s:dein_base_dir = expand('$CACHE/dein')
let s:dein_dir = expand(s:dein_base_dir .. '/repos/github.com/Shougo/dein.vim')

if &runtimepath !~# '/dein.vim'
  if !isdirectory(s:dein_dir)
    echo 'install dein.vim'
    execute '!git clone https://github.com/Shougo/dein.vim' s:dein_dir
  endif

  execute 'set runtimepath^=' . substitute(fnamemodify(s:dein_dir, ':p'), '[/\\]$', '', '')
endif



if dein#min#load_state(s:dein_base_dir)
  call dein#begin(s:dein_base_dir)

  call dein#add('Shougo/dein.vim')
  call dein#add('Shougo/cmdline.vim')

  call dein#end()

  call dein#save_state()
endif

if has('vim_starting') && dein#check_install()
  call dein#install()
endif


" }}}

if has('syntax')
  syntax on
endif

set title
set number

set background=light
set termguicolors
colorscheme shine
" colorscheme pablo
set backspace=indent,eol,start

```

**Comment by Shougo** [comment]
Hm...  It seems neovim's bug.  It does work when Vim.

**Comment by Shougo** [comment]
I have tested it.

```vim
set rtp+=~/work/cmdline.vim

call cmdline#input('')
```

The hidden text does not work when neovim starting.  But it works after neovim lunch.

**Comment by Shougo** [comment]
I have tested it and it works.

```vim
set rtp+=~/work/cmdline.vim

set title
set number

set background=light
set termguicolors
colorscheme shine

call cmdline#input('')
```

**Comment by Shougo** [comment]
> Vim or Neovim: Neovim v0.11.0-dev-401+gbcb17689d

it seems old.  Please use the latest version.

**Comment by Shougo** [comment]
OK.  I get it.  It is not the problem of `the prompt is displayed even in the original command line`.

**Comment by Shougo** [comment]
Fixed.
