### ISSUE TITLE
(WIP) Broken highlight for original cmdline window (with specific colorschme)

### ISSUE THREAD

**Issue by peacock0803sz** [Shougo/cmdline.vim#6]
# Problem

Highlight for original cmdline window goes forcely black at specific light-system colorscheme (like the screenshot)

![CleanShot 20240727-190837@2x](https://github.com/user-attachments/assets/439eda26-430c-450f-86bc-cbdf79573496)

# Step to Repro

Clone `catppuccin/nvim` colorschme (<https://github.com/catppuccin/nvim>) and use `.vimrc` like bellow:

```vim
set runtimepath+=/path/to/Shougo/cmdline.vim/
set runtimepath+=/path/to/catppuccin/nvim/

call cmdline#set_option(#{
      \ highlight_window: 'None',
      \ })

lua <<EOF
require("catppuccin").setup({
  flavour = "latte",
  transparent_background = true,
})
vim.cmd.colorscheme("catppuccin")
EOF

autocmd CmdlineEnter * call cmdline#enable()
```

**Comment by Shougo** [comment]
Reproduced.  But it is feature.
You use `transparent_background` feature.  `cmdline.vim` cannot hide the original command line.
